# Cloudflare Pages Configuration
name = "yoto-playlist-creator-web"
compatibility_date = "2024-01-01"

[env.production.build]
command = "npm run build"
cwd = ""

[env.production.build.upload]
format = "directory"
dir = "./dist"

[env.preview.build]
command = "npm run build"
cwd = ""

[env.preview.build.upload]
format = "directory"
dir = "./dist"