name = "yoto-playlist-creator-web"
main = "src/worker.js"
compatibility_date = "2025-09-05"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 0.1

[vars]
VITE_YOTO_REDIRECT_URI = "https://yoto-playlist-creator-web.jimmeh.workers.dev/auth/callback"